title: Ying(Veronica) Huang # your name (or website title) here
logo: "/images/BFF7A926-FEFA-4D38-B3E8-D830350B59C1.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am Veronica, an innovative data analyst and a self-motivated learner. It's my belief that data make up this world and can change this world!
  <br><br>
  Technical skills: SQL, Python, R, Tableau, AWS(Redshift, S3, EC2)
  <br><br>
  <a href="www.linkedin.com/in/ying-huang-msma">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
